---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Change permission on {{ osx_script }} file
  file:
    path: "{{ dotfiles_repo_local_destination }}/.osx"
    state: file
    mode: 0755

- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false
